export const languages = [
  { code: "af", name: "Afrikaans", voice: "af-ZA" },
  { code: "sq", name: "Albanian", voice: "sq-AL" },
  { code: "am", name: "Amharic", voice: "am-ET" },
  { code: "ar", name: "Arabic", voice: "ar-XA" },
  { code: "hy", name: "Armenian", voice: "hy-AM" },
  { code: "az", name: "Azerbaijani", voice: "az-AZ" },
  { code: "eu", name: "Basque", voice: "eu-ES" },
  { code: "be", name: "Belarusian", voice: "be-BY" },
  { code: "bn", name: "Bengali", voice: "bn-IN" },
  { code: "bs", name: "Bosnian", voice: "bs-BA" },
  { code: "bg", name: "Bulgarian", voice: "bg-BG" },
  { code: "ca", name: "Catalan", voice: "ca-ES" },
  { code: "ceb", name: "Cebuano", voice: "ceb-PH" },
  { code: "zh", name: "Chinese (Simplified)", voice: "zh-CN" },
  { code: "zh-TW", name: "Chinese (Traditional)", voice: "zh-TW" },
  { code: "co", name: "Corsican", voice: "co-FR" },
  { code: "hr", name: "Croatian", voice: "hr-HR" },
  { code: "cs", name: "Czech", voice: "cs-CZ" },
  { code: "da", name: "Danish", voice: "da-DK" },
  { code: "nl", name: "Dutch", voice: "nl-NL" },
  { code: "en", name: "English", voice: "en-US" },
  { code: "eo", name: "Esperanto", voice: "eo-EO" },
  { code: "et", name: "Estonian", voice: "et-EE" },
  { code: "fi", name: "Finnish", voice: "fi-FI" },
  { code: "fr", name: "French", voice: "fr-FR" },
  { code: "fy", name: "Frisian", voice: "fy-NL" },
  { code: "gl", name: "Galician", voice: "gl-ES" },
  { code: "ka", name: "Georgian", voice: "ka-GE" },
  { code: "de", name: "German", voice: "de-DE" },
  { code: "el", name: "Greek", voice: "el-GR" },
  { code: "gu", name: "Gujarati", voice: "gu-IN" },
  { code: "ht", name: "Haitian Creole", voice: "ht-HT" },
  { code: "ha", name: "Hausa", voice: "ha-NE" },
  { code: "haw", name: "Hawaiian", voice: "haw-US" },
  { code: "he", name: "Hebrew", voice: "he-IL" },
  { code: "hi", name: "Hindi", voice: "hi-IN" },
  { code: "hmn", name: "Hmong", voice: "hmn-US" },
  { code: "hu", name: "Hungarian", voice: "hu-HU" },
  { code: "is", name: "Icelandic", voice: "is-IS" },
  { code: "id", name: "Indonesian", voice: "id-ID" },
  { code: "ga", name: "Irish", voice: "ga-IE" },
  { code: "it", name: "Italian", voice: "it-IT" },
  { code: "ja", name: "Japanese", voice: "ja-JP" },
  { code: "jv", name: "Javanese", voice: "jv-ID" },
  { code: "kn", name: "Kannada", voice: "kn-IN" },
  { code: "kk", name: "Kazakh", voice: "kk-KZ" },
  { code: "km", name: "Khmer", voice: "km-KH" },
  { code: "ko", name: "Korean", voice: "ko-KR" },
  { code: "ku", name: "Kurdish", voice: "ku-TR" },
  { code: "ky", name: "Kyrgyz", voice: "ky-KG" },
  { code: "lo", name: "Lao", voice: "lo-LA" },
  { code: "la", name: "Latin", voice: "la-VA" },
  { code: "lv", name: "Latvian", voice: "lv-LV" },
  { code: "lt", name: "Lithuanian", voice: "lt-LT" },
  { code: "lb", name: "Luxembourgish", voice: "lb-LU" },
  { code: "mk", name: "Macedonian", voice: "mk-MK" },
  { code: "mg", name: "Malagasy", voice: "mg-MG" },
  { code: "ms", name: "Malay", voice: "ms-MY" },
  { code: "ml", name: "Malayalam", voice: "ml-IN" },
  { code: "mt", name: "Maltese", voice: "mt-MT" },
  { code: "mi", name: "Maori", voice: "mi-NZ" },
  { code: "mr", name: "Marathi", voice: "mr-IN" },
  { code: "mn", name: "Mongolian", voice: "mn-MN" },
  { code: "my", name: "Myanmar (Burmese)", voice: "my-MM" },
  { code: "ne", name: "Nepali", voice: "ne-NP" },
  { code: "no", name: "Norwegian", voice: "no-NO" },
  { code: "ny", name: "Nyanja (Chichewa)", voice: "ny-MW" },
  { code: "or", name: "Odia (Oriya)", voice: "or-IN" },
  { code: "ps", name: "Pashto", voice: "ps-AF" },
  { code: "fa", name: "Persian", voice: "fa-IR" },
  { code: "pl", name: "Polish", voice: "pl-PL" },
  { code: "pt", name: "Portuguese", voice: "pt-PT" },
  { code: "pa", name: "Punjabi", voice: "pa-IN" },
  { code: "ro", name: "Romanian", voice: "ro-RO" },
  { code: "ru", name: "Russian", voice: "ru-RU" },
  { code: "sm", name: "Samoan", voice: "sm-WS" },
  { code: "gd", name: "Scots Gaelic", voice: "gd-GB" },
  { code: "sr", name: "Serbian", voice: "sr-RS" },
  { code: "st", name: "Sesotho", voice: "st-LS" },
  { code: "sn", name: "Shona", voice: "sn-ZW" },
  { code: "sd", name: "Sindhi", voice: "sd-PK" },
  { code: "si", name: "Sinhala (Sinhalese)", voice: "si-LK" },
  { code: "sk", name: "Slovak", voice: "sk-SK" },
  { code: "sl", name: "Slovenian", voice: "sl-SI" },
  { code: "so", name: "Somali", voice: "so-SO" },
  { code: "es", name: "Spanish", voice: "es-ES" },
  { code: "su", name: "Sundanese", voice: "su-ID" },
  { code: "sw", name: "Swahili", voice: "sw-KE" },
  { code: "sv", name: "Swedish", voice: "sv-SE" },
  { code: "tl", name: "Tagalog (Filipino)", voice: "tl-PH" },
  { code: "tg", name: "Tajik", voice: "tg-TJ" },
  { code: "ta", name: "Tamil", voice: "ta-IN" },
  { code: "tt", name: "Tatar", voice: "tt-RU" },
  { code: "te", name: "Telugu", voice: "te-IN" },
  { code: "th", name: "Thai", voice: "th-TH" },
  { code: "tr", name: "Turkish", voice: "tr-TR" },
  { code: "tk", name: "Turkmen", voice: "tk-TM" },
  { code: "uk", name: "Ukrainian", voice: "uk-UA" },
  { code: "ur", name: "Urdu", voice: "ur-IN" },
  { code: "ug", name: "Uyghur", voice: "ug-CN" },
  { code: "uz", name: "Uzbek", voice: "uz-UZ" },
  { code: "vi", name: "Vietnamese", voice: "vi-VN" },
  { code: "cy", name: "Welsh", voice: "cy-GB" },
  { code: "xh", name: "Xhosa", voice: "xh-ZA" },
  { code: "yi", name: "Yiddish", voice: "yi-001" },
  { code: "yo", name: "Yoruba", voice: "yo-NG" },
  { code: "zu", name: "Zulu", voice: "zu-ZA" },
];
